version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    env_file: .env
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: anatolykuznec/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    env_file: .env
    image: anatolykuznec/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: anatolykuznec/foodgram_nginx
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend